### ISSUE TITLE
[feat] change api for widget

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/cache-element#15]
```js
const widget = require('cache-element/widget')

module.exports = createWidget

function createWidget () {
  // variables are bound in the closure
  return widget({
    onload: function () {
    },
    onunload: function () {
    },
    onupdate: function (link) {
    },
    render: function () {
      // return html
    }
  })
}
```
Closer to react's stateful components but without all the `this` stuff - also heaps less confusing and relying on implicit ordering of things

**Comment by timwis** [comment]
Hm, the only downside here is that you can't just wrap your bel element in this to widgetize it if you use `onload` in the bel way -- you have to pull your `onload` callback out to the top level. Although it's already a bit different due to #10

**Comment by yoshuawuyts** [comment]
Yeah using onload in the bel way is problematic - right now there's no
reliable way to find out if it's got an onload / unonload hook so it'll
have to conflict unfortunately - tbh I might maybe be in favor of stripping
out onload from bel entirely as using it with yo-yo it needs to be cached
anyway :/

**Comment by yoshuawuyts** [comment]
`v2.0.0`
