### ISSUE TITLE
[feat] new element: pure

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/cache-element#17]
As @emmak pointed out having a pure render element would be cool - cache vanilla elements:
```js
var pure = require('cache-element/pure')
var html = require('bel')

// this element is now cached without complicated comparisons
var el = Element()

function Element () {
  return pure(html`
    <section>
      <p>Hello world</p>
      <p>Hello planet</p>
    </section>
  `)
}
```
Feedback would be great!

**Comment by timwis** [comment]
What's the advantage of wrapping it? Would another example be a leaflet map that you know isn't going to need to change? When I saw the word `pure` I assumed it had to do with "pure functions"

**Comment by yoshuawuyts** [comment]
E.g. you could wrap an image tag that might accidentally request a new
image on every render, and things like that. The point would be that every
node down the tree won't be recomputed on render so it'll be super fast to
re-render; basically cutting down a branch in the render tree.

**Comment by yoshuawuyts** [comment]
Done, `v3.0.0`
