### ISSUE TITLE
bel independence

### ISSUE THREAD

**Issue by reminyborg** [yoshuawuyts/cache-element#8]
The first sentence in the README is

> Cache a bel element.

But this lib can be used with anything as long as it creates a DOM element.
I think we should make it at least apparent.

Ex:

``` javascript
function createEl (name, age) {
  var element = document.createElement('p')
  element.innerHTML = `The person's name is ${name}`
  return element
}
```

Thoughts? 😃

**Comment by yoshuawuyts** [comment]
yup, in reality the only hard demand is `morphdom` so switching the narrative makes sense :sparkles:

**Comment by yoshuawuyts** [comment]
hah, yeah that's fair - perhaps the phrasing should be more along the lines
of:
"cache a DOM element for use in morphdom" or something like that.

whichever phrasing you decide is best, PR welcome! ✨

**Comment by yoshuawuyts** [comment]
seems like my emails from a few days ago are finally coming through 😓 -
sorry about that

**Comment by yoshuawuyts** [comment]
lol, finally came around to this - done!
