### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by timwis** [yoshuawuyts/cache-element#9]
Has anyone got a working example of this module? I'm trying to use it with leaflet and the examples in the readme don't appear to work.

**Comment by paulsonnentag** [comment]
Here is a sample where I've used cache-element/widget: https://github.com/hdm-project/robot-ide/blob/develop/src/blockly.js

**Comment by timwis** [comment]
Thanks @paulsonnentag! The gotcha was that your "widget" cannot have `onload` in the parent element -- you have to put it in a child element, since `cache-element` adds its own `onload` property to the element that the widget returns. Bit of a gotcha.

I put up a demo repo of how to use this with leaflet: https://github.com/timwis/choo-leaflet-demo

EDIT: Oh, lol, looks like you discovered that to, just saw #10

**Comment by yoshuawuyts** [comment]
feels like a bug; it means we cannot attach two onload calls to the same
element - should probably file on bel / the load handler; this was
something I was worried might happen :/
